[workspace]
members = [
    "sidereal",
    "replication-server",
    "shard-server"
]
resolver = "2"

[workspace.dependencies]
bevy = "0.15.3"
bevy_state = "0.15"
bevy_reflect = "0.15.3"
bevy_replicon = "0.32"
bevy_replicon_renet2 = "0.7.0"
bevy_renet2 = "0.7.0"
renet2 = { version = "0.7.0"}

bincode ={version = "2.0.1", features = ["serde"] }
env_logger = "0.11.7"
serde_json = "1.0.140"
tracing = "0.1.41"
tokio = "1.44.1"

serde = { version = "1.0.219", features = ["derive"] }
uuid = { version = "1.12.1", features = ["v4", "serde"] }

[profile.dev]
opt-level = 3
debug = false
strip = false

[profile.release]
#opt-level = 's'
debug = false
lto = true
codegen-units = 1 #will slow down compilation considerably (+43%)
strip = true