[workspace]
members = [
    "sidereal-core",
    "sidereal-replication-server",
    "sidereal-shard-server",
    "sidereal-test-client"
]
resolver = "2"

[workspace.dependencies]
bevy = "0.15.0"
bevy_renet2 = "0.5.0"
renet2_netcode = "0.5.0"
env_logger = "0.11.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.36", features = ["full"] }
