[workspace]
members = [
    "sidereal-core",
    "sidereal-replication-server",
    "sidereal-shard-server",
    "sidereal-test-client"
]
resolver = "2"

[workspace.dependencies]
bevy = "0.15.3"
bevy_renet2 = "0.5.0"
renet2_netcode = "0.5.0"
env_logger = "0.11.6"
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.139"
tokio = { version = "1.43.0", features = ["full"] }
