# Cargo.toml
[package]
name = "sidereal-shard-server"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { workspace = true }
bevy_state = {workspace= true}
bevy_replicon = {workspace = true}
bevy_replicon_renet2 = {workspace = true}
bevy_remote = "0.15.3"

serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
uuid = {workspace = true }
bincode = {workspace = true }
tracing = {workspace = true}


tracing-subscriber = "0.3"
avian2d = "0.2.1"
dotenv = "0.15.0"

sidereal = { path = "../sidereal" }

[features]
default = []