/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShaderWorkbenchRouteImport } from './routes/shader-workbench'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard.index'
import { Route as ApiShadersRouteImport } from './routes/api.shaders'
import { Route as ApiGraphRouteImport } from './routes/api.graph'
import { Route as ApiDatabaseRouteImport } from './routes/api.database'
import { Route as ApiDashboardSessionRouteImport } from './routes/api.dashboard-session'
import { Route as ApiBrpRouteImport } from './routes/api.brp'
import { Route as DashboardSoundStudioRouteImport } from './routes/_dashboard.sound-studio'
import { Route as DashboardShaderWorkshopRouteImport } from './routes/_dashboard.shader-workshop'
import { Route as DashboardSettingsRouteImport } from './routes/_dashboard.settings'
import { Route as DashboardScriptEditorRouteImport } from './routes/_dashboard.script-editor'
import { Route as DashboardGenesisRouteImport } from './routes/_dashboard.genesis'
import { Route as DashboardGameWorldRouteImport } from './routes/_dashboard.game-world'
import { Route as DashboardGameClientRouteImport } from './routes/_dashboard.game-client'
import { Route as DashboardDatabaseRouteImport } from './routes/_dashboard.database'
import { Route as DashboardDatabaseIndexRouteImport } from './routes/_dashboard.database.index'
import { Route as ApiShadersUploadRouteImport } from './routes/api.shaders.upload'
import { Route as ApiShadersShaderIdRouteImport } from './routes/api.shaders.$shaderId'
import { Route as ApiGenesisPlanetsRouteImport } from './routes/api.genesis.planets'
import { Route as ApiDeleteEntityEntityIdRouteImport } from './routes/api.delete-entity.$entityId'
import { Route as ApiAudioCuesSoundIdRouteImport } from './routes/api.audio-cues.$soundId'
import { Route as ApiAdminSpawnEntityRouteImport } from './routes/api.admin.spawn-entity'
import { Route as DashboardSoundStudioSoundIdRouteImport } from './routes/_dashboard.sound-studio.$soundId'
import { Route as DashboardShaderWorkshopShaderIdRouteImport } from './routes/_dashboard.shader-workshop.$shaderId'
import { Route as DashboardGameWorldEntityGuidRouteImport } from './routes/_dashboard.game-world.$entityGuid'
import { Route as DashboardDatabaseTablesRouteImport } from './routes/_dashboard.database.tables'
import { Route as DashboardDatabaseAccountsRouteImport } from './routes/_dashboard.database.accounts'
import { Route as DashboardDatabaseEntityGuidRouteImport } from './routes/_dashboard.database.$entityGuid'
import { Route as ApiGenesisPlanetsPlanetIdPublishRouteImport } from './routes/api.genesis.planets.$planetId.publish'
import { Route as ApiGenesisPlanetsPlanetIdDraftRouteImport } from './routes/api.genesis.planets.$planetId.draft'
import { Route as ApiDatabaseCharactersPlayerEntityIdDisplayNameRouteImport } from './routes/api.database.characters.$playerEntityId.display-name'
import { Route as ApiDatabaseAccountsAccountIdPasswordResetRouteImport } from './routes/api.database.accounts.$accountId.password-reset'

const ShaderWorkbenchRoute = ShaderWorkbenchRouteImport.update({
  id: '/shader-workbench',
  path: '/shader-workbench',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiShadersRoute = ApiShadersRouteImport.update({
  id: '/api/shaders',
  path: '/api/shaders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGraphRoute = ApiGraphRouteImport.update({
  id: '/api/graph',
  path: '/api/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDatabaseRoute = ApiDatabaseRouteImport.update({
  id: '/api/database',
  path: '/api/database',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardSessionRoute = ApiDashboardSessionRouteImport.update({
  id: '/api/dashboard-session',
  path: '/api/dashboard-session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBrpRoute = ApiBrpRouteImport.update({
  id: '/api/brp',
  path: '/api/brp',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSoundStudioRoute = DashboardSoundStudioRouteImport.update({
  id: '/sound-studio',
  path: '/sound-studio',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardShaderWorkshopRoute = DashboardShaderWorkshopRouteImport.update({
  id: '/shader-workshop',
  path: '/shader-workshop',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardScriptEditorRoute = DashboardScriptEditorRouteImport.update({
  id: '/script-editor',
  path: '/script-editor',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGenesisRoute = DashboardGenesisRouteImport.update({
  id: '/genesis',
  path: '/genesis',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGameWorldRoute = DashboardGameWorldRouteImport.update({
  id: '/game-world',
  path: '/game-world',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGameClientRoute = DashboardGameClientRouteImport.update({
  id: '/game-client',
  path: '/game-client',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDatabaseRoute = DashboardDatabaseRouteImport.update({
  id: '/database',
  path: '/database',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDatabaseIndexRoute = DashboardDatabaseIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardDatabaseRoute,
} as any)
const ApiShadersUploadRoute = ApiShadersUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => ApiShadersRoute,
} as any)
const ApiShadersShaderIdRoute = ApiShadersShaderIdRouteImport.update({
  id: '/$shaderId',
  path: '/$shaderId',
  getParentRoute: () => ApiShadersRoute,
} as any)
const ApiGenesisPlanetsRoute = ApiGenesisPlanetsRouteImport.update({
  id: '/api/genesis/planets',
  path: '/api/genesis/planets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDeleteEntityEntityIdRoute = ApiDeleteEntityEntityIdRouteImport.update({
  id: '/api/delete-entity/$entityId',
  path: '/api/delete-entity/$entityId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAudioCuesSoundIdRoute = ApiAudioCuesSoundIdRouteImport.update({
  id: '/api/audio-cues/$soundId',
  path: '/api/audio-cues/$soundId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSpawnEntityRoute = ApiAdminSpawnEntityRouteImport.update({
  id: '/api/admin/spawn-entity',
  path: '/api/admin/spawn-entity',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSoundStudioSoundIdRoute =
  DashboardSoundStudioSoundIdRouteImport.update({
    id: '/$soundId',
    path: '/$soundId',
    getParentRoute: () => DashboardSoundStudioRoute,
  } as any)
const DashboardShaderWorkshopShaderIdRoute =
  DashboardShaderWorkshopShaderIdRouteImport.update({
    id: '/$shaderId',
    path: '/$shaderId',
    getParentRoute: () => DashboardShaderWorkshopRoute,
  } as any)
const DashboardGameWorldEntityGuidRoute =
  DashboardGameWorldEntityGuidRouteImport.update({
    id: '/$entityGuid',
    path: '/$entityGuid',
    getParentRoute: () => DashboardGameWorldRoute,
  } as any)
const DashboardDatabaseTablesRoute = DashboardDatabaseTablesRouteImport.update({
  id: '/tables',
  path: '/tables',
  getParentRoute: () => DashboardDatabaseRoute,
} as any)
const DashboardDatabaseAccountsRoute =
  DashboardDatabaseAccountsRouteImport.update({
    id: '/accounts',
    path: '/accounts',
    getParentRoute: () => DashboardDatabaseRoute,
  } as any)
const DashboardDatabaseEntityGuidRoute =
  DashboardDatabaseEntityGuidRouteImport.update({
    id: '/$entityGuid',
    path: '/$entityGuid',
    getParentRoute: () => DashboardDatabaseRoute,
  } as any)
const ApiGenesisPlanetsPlanetIdPublishRoute =
  ApiGenesisPlanetsPlanetIdPublishRouteImport.update({
    id: '/$planetId/publish',
    path: '/$planetId/publish',
    getParentRoute: () => ApiGenesisPlanetsRoute,
  } as any)
const ApiGenesisPlanetsPlanetIdDraftRoute =
  ApiGenesisPlanetsPlanetIdDraftRouteImport.update({
    id: '/$planetId/draft',
    path: '/$planetId/draft',
    getParentRoute: () => ApiGenesisPlanetsRoute,
  } as any)
const ApiDatabaseCharactersPlayerEntityIdDisplayNameRoute =
  ApiDatabaseCharactersPlayerEntityIdDisplayNameRouteImport.update({
    id: '/characters/$playerEntityId/display-name',
    path: '/characters/$playerEntityId/display-name',
    getParentRoute: () => ApiDatabaseRoute,
  } as any)
const ApiDatabaseAccountsAccountIdPasswordResetRoute =
  ApiDatabaseAccountsAccountIdPasswordResetRouteImport.update({
    id: '/accounts/$accountId/password-reset',
    path: '/accounts/$accountId/password-reset',
    getParentRoute: () => ApiDatabaseRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof DashboardIndexRoute
  '/shader-workbench': typeof ShaderWorkbenchRoute
  '/database': typeof DashboardDatabaseRouteWithChildren
  '/game-client': typeof DashboardGameClientRoute
  '/game-world': typeof DashboardGameWorldRouteWithChildren
  '/genesis': typeof DashboardGenesisRoute
  '/script-editor': typeof DashboardScriptEditorRoute
  '/settings': typeof DashboardSettingsRoute
  '/shader-workshop': typeof DashboardShaderWorkshopRouteWithChildren
  '/sound-studio': typeof DashboardSoundStudioRouteWithChildren
  '/api/brp': typeof ApiBrpRoute
  '/api/dashboard-session': typeof ApiDashboardSessionRoute
  '/api/database': typeof ApiDatabaseRouteWithChildren
  '/api/graph': typeof ApiGraphRoute
  '/api/shaders': typeof ApiShadersRouteWithChildren
  '/database/$entityGuid': typeof DashboardDatabaseEntityGuidRoute
  '/database/accounts': typeof DashboardDatabaseAccountsRoute
  '/database/tables': typeof DashboardDatabaseTablesRoute
  '/game-world/$entityGuid': typeof DashboardGameWorldEntityGuidRoute
  '/shader-workshop/$shaderId': typeof DashboardShaderWorkshopShaderIdRoute
  '/sound-studio/$soundId': typeof DashboardSoundStudioSoundIdRoute
  '/api/admin/spawn-entity': typeof ApiAdminSpawnEntityRoute
  '/api/audio-cues/$soundId': typeof ApiAudioCuesSoundIdRoute
  '/api/delete-entity/$entityId': typeof ApiDeleteEntityEntityIdRoute
  '/api/genesis/planets': typeof ApiGenesisPlanetsRouteWithChildren
  '/api/shaders/$shaderId': typeof ApiShadersShaderIdRoute
  '/api/shaders/upload': typeof ApiShadersUploadRoute
  '/database/': typeof DashboardDatabaseIndexRoute
  '/api/database/accounts/$accountId/password-reset': typeof ApiDatabaseAccountsAccountIdPasswordResetRoute
  '/api/database/characters/$playerEntityId/display-name': typeof ApiDatabaseCharactersPlayerEntityIdDisplayNameRoute
  '/api/genesis/planets/$planetId/draft': typeof ApiGenesisPlanetsPlanetIdDraftRoute
  '/api/genesis/planets/$planetId/publish': typeof ApiGenesisPlanetsPlanetIdPublishRoute
}
export interface FileRoutesByTo {
  '/shader-workbench': typeof ShaderWorkbenchRoute
  '/game-client': typeof DashboardGameClientRoute
  '/game-world': typeof DashboardGameWorldRouteWithChildren
  '/genesis': typeof DashboardGenesisRoute
  '/script-editor': typeof DashboardScriptEditorRoute
  '/settings': typeof DashboardSettingsRoute
  '/shader-workshop': typeof DashboardShaderWorkshopRouteWithChildren
  '/sound-studio': typeof DashboardSoundStudioRouteWithChildren
  '/api/brp': typeof ApiBrpRoute
  '/api/dashboard-session': typeof ApiDashboardSessionRoute
  '/api/database': typeof ApiDatabaseRouteWithChildren
  '/api/graph': typeof ApiGraphRoute
  '/api/shaders': typeof ApiShadersRouteWithChildren
  '/': typeof DashboardIndexRoute
  '/database/$entityGuid': typeof DashboardDatabaseEntityGuidRoute
  '/database/accounts': typeof DashboardDatabaseAccountsRoute
  '/database/tables': typeof DashboardDatabaseTablesRoute
  '/game-world/$entityGuid': typeof DashboardGameWorldEntityGuidRoute
  '/shader-workshop/$shaderId': typeof DashboardShaderWorkshopShaderIdRoute
  '/sound-studio/$soundId': typeof DashboardSoundStudioSoundIdRoute
  '/api/admin/spawn-entity': typeof ApiAdminSpawnEntityRoute
  '/api/audio-cues/$soundId': typeof ApiAudioCuesSoundIdRoute
  '/api/delete-entity/$entityId': typeof ApiDeleteEntityEntityIdRoute
  '/api/genesis/planets': typeof ApiGenesisPlanetsRouteWithChildren
  '/api/shaders/$shaderId': typeof ApiShadersShaderIdRoute
  '/api/shaders/upload': typeof ApiShadersUploadRoute
  '/database': typeof DashboardDatabaseIndexRoute
  '/api/database/accounts/$accountId/password-reset': typeof ApiDatabaseAccountsAccountIdPasswordResetRoute
  '/api/database/characters/$playerEntityId/display-name': typeof ApiDatabaseCharactersPlayerEntityIdDisplayNameRoute
  '/api/genesis/planets/$planetId/draft': typeof ApiGenesisPlanetsPlanetIdDraftRoute
  '/api/genesis/planets/$planetId/publish': typeof ApiGenesisPlanetsPlanetIdPublishRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteWithChildren
  '/shader-workbench': typeof ShaderWorkbenchRoute
  '/_dashboard/database': typeof DashboardDatabaseRouteWithChildren
  '/_dashboard/game-client': typeof DashboardGameClientRoute
  '/_dashboard/game-world': typeof DashboardGameWorldRouteWithChildren
  '/_dashboard/genesis': typeof DashboardGenesisRoute
  '/_dashboard/script-editor': typeof DashboardScriptEditorRoute
  '/_dashboard/settings': typeof DashboardSettingsRoute
  '/_dashboard/shader-workshop': typeof DashboardShaderWorkshopRouteWithChildren
  '/_dashboard/sound-studio': typeof DashboardSoundStudioRouteWithChildren
  '/api/brp': typeof ApiBrpRoute
  '/api/dashboard-session': typeof ApiDashboardSessionRoute
  '/api/database': typeof ApiDatabaseRouteWithChildren
  '/api/graph': typeof ApiGraphRoute
  '/api/shaders': typeof ApiShadersRouteWithChildren
  '/_dashboard/': typeof DashboardIndexRoute
  '/_dashboard/database/$entityGuid': typeof DashboardDatabaseEntityGuidRoute
  '/_dashboard/database/accounts': typeof DashboardDatabaseAccountsRoute
  '/_dashboard/database/tables': typeof DashboardDatabaseTablesRoute
  '/_dashboard/game-world/$entityGuid': typeof DashboardGameWorldEntityGuidRoute
  '/_dashboard/shader-workshop/$shaderId': typeof DashboardShaderWorkshopShaderIdRoute
  '/_dashboard/sound-studio/$soundId': typeof DashboardSoundStudioSoundIdRoute
  '/api/admin/spawn-entity': typeof ApiAdminSpawnEntityRoute
  '/api/audio-cues/$soundId': typeof ApiAudioCuesSoundIdRoute
  '/api/delete-entity/$entityId': typeof ApiDeleteEntityEntityIdRoute
  '/api/genesis/planets': typeof ApiGenesisPlanetsRouteWithChildren
  '/api/shaders/$shaderId': typeof ApiShadersShaderIdRoute
  '/api/shaders/upload': typeof ApiShadersUploadRoute
  '/_dashboard/database/': typeof DashboardDatabaseIndexRoute
  '/api/database/accounts/$accountId/password-reset': typeof ApiDatabaseAccountsAccountIdPasswordResetRoute
  '/api/database/characters/$playerEntityId/display-name': typeof ApiDatabaseCharactersPlayerEntityIdDisplayNameRoute
  '/api/genesis/planets/$planetId/draft': typeof ApiGenesisPlanetsPlanetIdDraftRoute
  '/api/genesis/planets/$planetId/publish': typeof ApiGenesisPlanetsPlanetIdPublishRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/shader-workbench'
    | '/database'
    | '/game-client'
    | '/game-world'
    | '/genesis'
    | '/script-editor'
    | '/settings'
    | '/shader-workshop'
    | '/sound-studio'
    | '/api/brp'
    | '/api/dashboard-session'
    | '/api/database'
    | '/api/graph'
    | '/api/shaders'
    | '/database/$entityGuid'
    | '/database/accounts'
    | '/database/tables'
    | '/game-world/$entityGuid'
    | '/shader-workshop/$shaderId'
    | '/sound-studio/$soundId'
    | '/api/admin/spawn-entity'
    | '/api/audio-cues/$soundId'
    | '/api/delete-entity/$entityId'
    | '/api/genesis/planets'
    | '/api/shaders/$shaderId'
    | '/api/shaders/upload'
    | '/database/'
    | '/api/database/accounts/$accountId/password-reset'
    | '/api/database/characters/$playerEntityId/display-name'
    | '/api/genesis/planets/$planetId/draft'
    | '/api/genesis/planets/$planetId/publish'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/shader-workbench'
    | '/game-client'
    | '/game-world'
    | '/genesis'
    | '/script-editor'
    | '/settings'
    | '/shader-workshop'
    | '/sound-studio'
    | '/api/brp'
    | '/api/dashboard-session'
    | '/api/database'
    | '/api/graph'
    | '/api/shaders'
    | '/'
    | '/database/$entityGuid'
    | '/database/accounts'
    | '/database/tables'
    | '/game-world/$entityGuid'
    | '/shader-workshop/$shaderId'
    | '/sound-studio/$soundId'
    | '/api/admin/spawn-entity'
    | '/api/audio-cues/$soundId'
    | '/api/delete-entity/$entityId'
    | '/api/genesis/planets'
    | '/api/shaders/$shaderId'
    | '/api/shaders/upload'
    | '/database'
    | '/api/database/accounts/$accountId/password-reset'
    | '/api/database/characters/$playerEntityId/display-name'
    | '/api/genesis/planets/$planetId/draft'
    | '/api/genesis/planets/$planetId/publish'
  id:
    | '__root__'
    | '/_dashboard'
    | '/shader-workbench'
    | '/_dashboard/database'
    | '/_dashboard/game-client'
    | '/_dashboard/game-world'
    | '/_dashboard/genesis'
    | '/_dashboard/script-editor'
    | '/_dashboard/settings'
    | '/_dashboard/shader-workshop'
    | '/_dashboard/sound-studio'
    | '/api/brp'
    | '/api/dashboard-session'
    | '/api/database'
    | '/api/graph'
    | '/api/shaders'
    | '/_dashboard/'
    | '/_dashboard/database/$entityGuid'
    | '/_dashboard/database/accounts'
    | '/_dashboard/database/tables'
    | '/_dashboard/game-world/$entityGuid'
    | '/_dashboard/shader-workshop/$shaderId'
    | '/_dashboard/sound-studio/$soundId'
    | '/api/admin/spawn-entity'
    | '/api/audio-cues/$soundId'
    | '/api/delete-entity/$entityId'
    | '/api/genesis/planets'
    | '/api/shaders/$shaderId'
    | '/api/shaders/upload'
    | '/_dashboard/database/'
    | '/api/database/accounts/$accountId/password-reset'
    | '/api/database/characters/$playerEntityId/display-name'
    | '/api/genesis/planets/$planetId/draft'
    | '/api/genesis/planets/$planetId/publish'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
  ShaderWorkbenchRoute: typeof ShaderWorkbenchRoute
  ApiBrpRoute: typeof ApiBrpRoute
  ApiDashboardSessionRoute: typeof ApiDashboardSessionRoute
  ApiDatabaseRoute: typeof ApiDatabaseRouteWithChildren
  ApiGraphRoute: typeof ApiGraphRoute
  ApiShadersRoute: typeof ApiShadersRouteWithChildren
  ApiAdminSpawnEntityRoute: typeof ApiAdminSpawnEntityRoute
  ApiAudioCuesSoundIdRoute: typeof ApiAudioCuesSoundIdRoute
  ApiDeleteEntityEntityIdRoute: typeof ApiDeleteEntityEntityIdRoute
  ApiGenesisPlanetsRoute: typeof ApiGenesisPlanetsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shader-workbench': {
      id: '/shader-workbench'
      path: '/shader-workbench'
      fullPath: '/shader-workbench'
      preLoaderRoute: typeof ShaderWorkbenchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/shaders': {
      id: '/api/shaders'
      path: '/api/shaders'
      fullPath: '/api/shaders'
      preLoaderRoute: typeof ApiShadersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/graph': {
      id: '/api/graph'
      path: '/api/graph'
      fullPath: '/api/graph'
      preLoaderRoute: typeof ApiGraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/database': {
      id: '/api/database'
      path: '/api/database'
      fullPath: '/api/database'
      preLoaderRoute: typeof ApiDatabaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard-session': {
      id: '/api/dashboard-session'
      path: '/api/dashboard-session'
      fullPath: '/api/dashboard-session'
      preLoaderRoute: typeof ApiDashboardSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/brp': {
      id: '/api/brp'
      path: '/api/brp'
      fullPath: '/api/brp'
      preLoaderRoute: typeof ApiBrpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/sound-studio': {
      id: '/_dashboard/sound-studio'
      path: '/sound-studio'
      fullPath: '/sound-studio'
      preLoaderRoute: typeof DashboardSoundStudioRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/shader-workshop': {
      id: '/_dashboard/shader-workshop'
      path: '/shader-workshop'
      fullPath: '/shader-workshop'
      preLoaderRoute: typeof DashboardShaderWorkshopRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/settings': {
      id: '/_dashboard/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/script-editor': {
      id: '/_dashboard/script-editor'
      path: '/script-editor'
      fullPath: '/script-editor'
      preLoaderRoute: typeof DashboardScriptEditorRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/genesis': {
      id: '/_dashboard/genesis'
      path: '/genesis'
      fullPath: '/genesis'
      preLoaderRoute: typeof DashboardGenesisRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/game-world': {
      id: '/_dashboard/game-world'
      path: '/game-world'
      fullPath: '/game-world'
      preLoaderRoute: typeof DashboardGameWorldRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/game-client': {
      id: '/_dashboard/game-client'
      path: '/game-client'
      fullPath: '/game-client'
      preLoaderRoute: typeof DashboardGameClientRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/database': {
      id: '/_dashboard/database'
      path: '/database'
      fullPath: '/database'
      preLoaderRoute: typeof DashboardDatabaseRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/database/': {
      id: '/_dashboard/database/'
      path: '/'
      fullPath: '/database/'
      preLoaderRoute: typeof DashboardDatabaseIndexRouteImport
      parentRoute: typeof DashboardDatabaseRoute
    }
    '/api/shaders/upload': {
      id: '/api/shaders/upload'
      path: '/upload'
      fullPath: '/api/shaders/upload'
      preLoaderRoute: typeof ApiShadersUploadRouteImport
      parentRoute: typeof ApiShadersRoute
    }
    '/api/shaders/$shaderId': {
      id: '/api/shaders/$shaderId'
      path: '/$shaderId'
      fullPath: '/api/shaders/$shaderId'
      preLoaderRoute: typeof ApiShadersShaderIdRouteImport
      parentRoute: typeof ApiShadersRoute
    }
    '/api/genesis/planets': {
      id: '/api/genesis/planets'
      path: '/api/genesis/planets'
      fullPath: '/api/genesis/planets'
      preLoaderRoute: typeof ApiGenesisPlanetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/delete-entity/$entityId': {
      id: '/api/delete-entity/$entityId'
      path: '/api/delete-entity/$entityId'
      fullPath: '/api/delete-entity/$entityId'
      preLoaderRoute: typeof ApiDeleteEntityEntityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/audio-cues/$soundId': {
      id: '/api/audio-cues/$soundId'
      path: '/api/audio-cues/$soundId'
      fullPath: '/api/audio-cues/$soundId'
      preLoaderRoute: typeof ApiAudioCuesSoundIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/spawn-entity': {
      id: '/api/admin/spawn-entity'
      path: '/api/admin/spawn-entity'
      fullPath: '/api/admin/spawn-entity'
      preLoaderRoute: typeof ApiAdminSpawnEntityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/sound-studio/$soundId': {
      id: '/_dashboard/sound-studio/$soundId'
      path: '/$soundId'
      fullPath: '/sound-studio/$soundId'
      preLoaderRoute: typeof DashboardSoundStudioSoundIdRouteImport
      parentRoute: typeof DashboardSoundStudioRoute
    }
    '/_dashboard/shader-workshop/$shaderId': {
      id: '/_dashboard/shader-workshop/$shaderId'
      path: '/$shaderId'
      fullPath: '/shader-workshop/$shaderId'
      preLoaderRoute: typeof DashboardShaderWorkshopShaderIdRouteImport
      parentRoute: typeof DashboardShaderWorkshopRoute
    }
    '/_dashboard/game-world/$entityGuid': {
      id: '/_dashboard/game-world/$entityGuid'
      path: '/$entityGuid'
      fullPath: '/game-world/$entityGuid'
      preLoaderRoute: typeof DashboardGameWorldEntityGuidRouteImport
      parentRoute: typeof DashboardGameWorldRoute
    }
    '/_dashboard/database/tables': {
      id: '/_dashboard/database/tables'
      path: '/tables'
      fullPath: '/database/tables'
      preLoaderRoute: typeof DashboardDatabaseTablesRouteImport
      parentRoute: typeof DashboardDatabaseRoute
    }
    '/_dashboard/database/accounts': {
      id: '/_dashboard/database/accounts'
      path: '/accounts'
      fullPath: '/database/accounts'
      preLoaderRoute: typeof DashboardDatabaseAccountsRouteImport
      parentRoute: typeof DashboardDatabaseRoute
    }
    '/_dashboard/database/$entityGuid': {
      id: '/_dashboard/database/$entityGuid'
      path: '/$entityGuid'
      fullPath: '/database/$entityGuid'
      preLoaderRoute: typeof DashboardDatabaseEntityGuidRouteImport
      parentRoute: typeof DashboardDatabaseRoute
    }
    '/api/genesis/planets/$planetId/publish': {
      id: '/api/genesis/planets/$planetId/publish'
      path: '/$planetId/publish'
      fullPath: '/api/genesis/planets/$planetId/publish'
      preLoaderRoute: typeof ApiGenesisPlanetsPlanetIdPublishRouteImport
      parentRoute: typeof ApiGenesisPlanetsRoute
    }
    '/api/genesis/planets/$planetId/draft': {
      id: '/api/genesis/planets/$planetId/draft'
      path: '/$planetId/draft'
      fullPath: '/api/genesis/planets/$planetId/draft'
      preLoaderRoute: typeof ApiGenesisPlanetsPlanetIdDraftRouteImport
      parentRoute: typeof ApiGenesisPlanetsRoute
    }
    '/api/database/characters/$playerEntityId/display-name': {
      id: '/api/database/characters/$playerEntityId/display-name'
      path: '/characters/$playerEntityId/display-name'
      fullPath: '/api/database/characters/$playerEntityId/display-name'
      preLoaderRoute: typeof ApiDatabaseCharactersPlayerEntityIdDisplayNameRouteImport
      parentRoute: typeof ApiDatabaseRoute
    }
    '/api/database/accounts/$accountId/password-reset': {
      id: '/api/database/accounts/$accountId/password-reset'
      path: '/accounts/$accountId/password-reset'
      fullPath: '/api/database/accounts/$accountId/password-reset'
      preLoaderRoute: typeof ApiDatabaseAccountsAccountIdPasswordResetRouteImport
      parentRoute: typeof ApiDatabaseRoute
    }
  }
}

interface DashboardDatabaseRouteChildren {
  DashboardDatabaseEntityGuidRoute: typeof DashboardDatabaseEntityGuidRoute
  DashboardDatabaseAccountsRoute: typeof DashboardDatabaseAccountsRoute
  DashboardDatabaseTablesRoute: typeof DashboardDatabaseTablesRoute
  DashboardDatabaseIndexRoute: typeof DashboardDatabaseIndexRoute
}

const DashboardDatabaseRouteChildren: DashboardDatabaseRouteChildren = {
  DashboardDatabaseEntityGuidRoute: DashboardDatabaseEntityGuidRoute,
  DashboardDatabaseAccountsRoute: DashboardDatabaseAccountsRoute,
  DashboardDatabaseTablesRoute: DashboardDatabaseTablesRoute,
  DashboardDatabaseIndexRoute: DashboardDatabaseIndexRoute,
}

const DashboardDatabaseRouteWithChildren =
  DashboardDatabaseRoute._addFileChildren(DashboardDatabaseRouteChildren)

interface DashboardGameWorldRouteChildren {
  DashboardGameWorldEntityGuidRoute: typeof DashboardGameWorldEntityGuidRoute
}

const DashboardGameWorldRouteChildren: DashboardGameWorldRouteChildren = {
  DashboardGameWorldEntityGuidRoute: DashboardGameWorldEntityGuidRoute,
}

const DashboardGameWorldRouteWithChildren =
  DashboardGameWorldRoute._addFileChildren(DashboardGameWorldRouteChildren)

interface DashboardShaderWorkshopRouteChildren {
  DashboardShaderWorkshopShaderIdRoute: typeof DashboardShaderWorkshopShaderIdRoute
}

const DashboardShaderWorkshopRouteChildren: DashboardShaderWorkshopRouteChildren =
  {
    DashboardShaderWorkshopShaderIdRoute: DashboardShaderWorkshopShaderIdRoute,
  }

const DashboardShaderWorkshopRouteWithChildren =
  DashboardShaderWorkshopRoute._addFileChildren(
    DashboardShaderWorkshopRouteChildren,
  )

interface DashboardSoundStudioRouteChildren {
  DashboardSoundStudioSoundIdRoute: typeof DashboardSoundStudioSoundIdRoute
}

const DashboardSoundStudioRouteChildren: DashboardSoundStudioRouteChildren = {
  DashboardSoundStudioSoundIdRoute: DashboardSoundStudioSoundIdRoute,
}

const DashboardSoundStudioRouteWithChildren =
  DashboardSoundStudioRoute._addFileChildren(DashboardSoundStudioRouteChildren)

interface DashboardRouteChildren {
  DashboardDatabaseRoute: typeof DashboardDatabaseRouteWithChildren
  DashboardGameClientRoute: typeof DashboardGameClientRoute
  DashboardGameWorldRoute: typeof DashboardGameWorldRouteWithChildren
  DashboardGenesisRoute: typeof DashboardGenesisRoute
  DashboardScriptEditorRoute: typeof DashboardScriptEditorRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardShaderWorkshopRoute: typeof DashboardShaderWorkshopRouteWithChildren
  DashboardSoundStudioRoute: typeof DashboardSoundStudioRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardDatabaseRoute: DashboardDatabaseRouteWithChildren,
  DashboardGameClientRoute: DashboardGameClientRoute,
  DashboardGameWorldRoute: DashboardGameWorldRouteWithChildren,
  DashboardGenesisRoute: DashboardGenesisRoute,
  DashboardScriptEditorRoute: DashboardScriptEditorRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardShaderWorkshopRoute: DashboardShaderWorkshopRouteWithChildren,
  DashboardSoundStudioRoute: DashboardSoundStudioRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface ApiDatabaseRouteChildren {
  ApiDatabaseAccountsAccountIdPasswordResetRoute: typeof ApiDatabaseAccountsAccountIdPasswordResetRoute
  ApiDatabaseCharactersPlayerEntityIdDisplayNameRoute: typeof ApiDatabaseCharactersPlayerEntityIdDisplayNameRoute
}

const ApiDatabaseRouteChildren: ApiDatabaseRouteChildren = {
  ApiDatabaseAccountsAccountIdPasswordResetRoute:
    ApiDatabaseAccountsAccountIdPasswordResetRoute,
  ApiDatabaseCharactersPlayerEntityIdDisplayNameRoute:
    ApiDatabaseCharactersPlayerEntityIdDisplayNameRoute,
}

const ApiDatabaseRouteWithChildren = ApiDatabaseRoute._addFileChildren(
  ApiDatabaseRouteChildren,
)

interface ApiShadersRouteChildren {
  ApiShadersShaderIdRoute: typeof ApiShadersShaderIdRoute
  ApiShadersUploadRoute: typeof ApiShadersUploadRoute
}

const ApiShadersRouteChildren: ApiShadersRouteChildren = {
  ApiShadersShaderIdRoute: ApiShadersShaderIdRoute,
  ApiShadersUploadRoute: ApiShadersUploadRoute,
}

const ApiShadersRouteWithChildren = ApiShadersRoute._addFileChildren(
  ApiShadersRouteChildren,
)

interface ApiGenesisPlanetsRouteChildren {
  ApiGenesisPlanetsPlanetIdDraftRoute: typeof ApiGenesisPlanetsPlanetIdDraftRoute
  ApiGenesisPlanetsPlanetIdPublishRoute: typeof ApiGenesisPlanetsPlanetIdPublishRoute
}

const ApiGenesisPlanetsRouteChildren: ApiGenesisPlanetsRouteChildren = {
  ApiGenesisPlanetsPlanetIdDraftRoute: ApiGenesisPlanetsPlanetIdDraftRoute,
  ApiGenesisPlanetsPlanetIdPublishRoute: ApiGenesisPlanetsPlanetIdPublishRoute,
}

const ApiGenesisPlanetsRouteWithChildren =
  ApiGenesisPlanetsRoute._addFileChildren(ApiGenesisPlanetsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
  ShaderWorkbenchRoute: ShaderWorkbenchRoute,
  ApiBrpRoute: ApiBrpRoute,
  ApiDashboardSessionRoute: ApiDashboardSessionRoute,
  ApiDatabaseRoute: ApiDatabaseRouteWithChildren,
  ApiGraphRoute: ApiGraphRoute,
  ApiShadersRoute: ApiShadersRouteWithChildren,
  ApiAdminSpawnEntityRoute: ApiAdminSpawnEntityRoute,
  ApiAudioCuesSoundIdRoute: ApiAudioCuesSoundIdRoute,
  ApiDeleteEntityEntityIdRoute: ApiDeleteEntityEntityIdRoute,
  ApiGenesisPlanetsRoute: ApiGenesisPlanetsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
