/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiWorldRouteImport } from './routes/api.world'
import { Route as ApiLiveWorldRouteImport } from './routes/api.live-world'
import { Route as ApiLiveClientWorldRouteImport } from './routes/api.live-client-world'
import { Route as ApiGraphRouteImport } from './routes/api.graph'
import { Route as ApiBrpRouteImport } from './routes/api.brp'
import { Route as ApiLiveEntityEntityIdRouteImport } from './routes/api.live-entity.$entityId'
import { Route as ApiDeleteLiveEntityEntityIdRouteImport } from './routes/api.delete-live-entity.$entityId'
import { Route as ApiDeleteEntityEntityIdRouteImport } from './routes/api.delete-entity.$entityId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorldRoute = ApiWorldRouteImport.update({
  id: '/api/world',
  path: '/api/world',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLiveWorldRoute = ApiLiveWorldRouteImport.update({
  id: '/api/live-world',
  path: '/api/live-world',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLiveClientWorldRoute = ApiLiveClientWorldRouteImport.update({
  id: '/api/live-client-world',
  path: '/api/live-client-world',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGraphRoute = ApiGraphRouteImport.update({
  id: '/api/graph',
  path: '/api/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBrpRoute = ApiBrpRouteImport.update({
  id: '/api/brp',
  path: '/api/brp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLiveEntityEntityIdRoute = ApiLiveEntityEntityIdRouteImport.update({
  id: '/api/live-entity/$entityId',
  path: '/api/live-entity/$entityId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDeleteLiveEntityEntityIdRoute =
  ApiDeleteLiveEntityEntityIdRouteImport.update({
    id: '/api/delete-live-entity/$entityId',
    path: '/api/delete-live-entity/$entityId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDeleteEntityEntityIdRoute = ApiDeleteEntityEntityIdRouteImport.update({
  id: '/api/delete-entity/$entityId',
  path: '/api/delete-entity/$entityId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/brp': typeof ApiBrpRoute
  '/api/graph': typeof ApiGraphRoute
  '/api/live-client-world': typeof ApiLiveClientWorldRoute
  '/api/live-world': typeof ApiLiveWorldRoute
  '/api/world': typeof ApiWorldRoute
  '/api/delete-entity/$entityId': typeof ApiDeleteEntityEntityIdRoute
  '/api/delete-live-entity/$entityId': typeof ApiDeleteLiveEntityEntityIdRoute
  '/api/live-entity/$entityId': typeof ApiLiveEntityEntityIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/brp': typeof ApiBrpRoute
  '/api/graph': typeof ApiGraphRoute
  '/api/live-client-world': typeof ApiLiveClientWorldRoute
  '/api/live-world': typeof ApiLiveWorldRoute
  '/api/world': typeof ApiWorldRoute
  '/api/delete-entity/$entityId': typeof ApiDeleteEntityEntityIdRoute
  '/api/delete-live-entity/$entityId': typeof ApiDeleteLiveEntityEntityIdRoute
  '/api/live-entity/$entityId': typeof ApiLiveEntityEntityIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/brp': typeof ApiBrpRoute
  '/api/graph': typeof ApiGraphRoute
  '/api/live-client-world': typeof ApiLiveClientWorldRoute
  '/api/live-world': typeof ApiLiveWorldRoute
  '/api/world': typeof ApiWorldRoute
  '/api/delete-entity/$entityId': typeof ApiDeleteEntityEntityIdRoute
  '/api/delete-live-entity/$entityId': typeof ApiDeleteLiveEntityEntityIdRoute
  '/api/live-entity/$entityId': typeof ApiLiveEntityEntityIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/brp'
    | '/api/graph'
    | '/api/live-client-world'
    | '/api/live-world'
    | '/api/world'
    | '/api/delete-entity/$entityId'
    | '/api/delete-live-entity/$entityId'
    | '/api/live-entity/$entityId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/brp'
    | '/api/graph'
    | '/api/live-client-world'
    | '/api/live-world'
    | '/api/world'
    | '/api/delete-entity/$entityId'
    | '/api/delete-live-entity/$entityId'
    | '/api/live-entity/$entityId'
  id:
    | '__root__'
    | '/'
    | '/api/brp'
    | '/api/graph'
    | '/api/live-client-world'
    | '/api/live-world'
    | '/api/world'
    | '/api/delete-entity/$entityId'
    | '/api/delete-live-entity/$entityId'
    | '/api/live-entity/$entityId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiBrpRoute: typeof ApiBrpRoute
  ApiGraphRoute: typeof ApiGraphRoute
  ApiLiveClientWorldRoute: typeof ApiLiveClientWorldRoute
  ApiLiveWorldRoute: typeof ApiLiveWorldRoute
  ApiWorldRoute: typeof ApiWorldRoute
  ApiDeleteEntityEntityIdRoute: typeof ApiDeleteEntityEntityIdRoute
  ApiDeleteLiveEntityEntityIdRoute: typeof ApiDeleteLiveEntityEntityIdRoute
  ApiLiveEntityEntityIdRoute: typeof ApiLiveEntityEntityIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/world': {
      id: '/api/world'
      path: '/api/world'
      fullPath: '/api/world'
      preLoaderRoute: typeof ApiWorldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/live-world': {
      id: '/api/live-world'
      path: '/api/live-world'
      fullPath: '/api/live-world'
      preLoaderRoute: typeof ApiLiveWorldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/live-client-world': {
      id: '/api/live-client-world'
      path: '/api/live-client-world'
      fullPath: '/api/live-client-world'
      preLoaderRoute: typeof ApiLiveClientWorldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/graph': {
      id: '/api/graph'
      path: '/api/graph'
      fullPath: '/api/graph'
      preLoaderRoute: typeof ApiGraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/brp': {
      id: '/api/brp'
      path: '/api/brp'
      fullPath: '/api/brp'
      preLoaderRoute: typeof ApiBrpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/live-entity/$entityId': {
      id: '/api/live-entity/$entityId'
      path: '/api/live-entity/$entityId'
      fullPath: '/api/live-entity/$entityId'
      preLoaderRoute: typeof ApiLiveEntityEntityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/delete-live-entity/$entityId': {
      id: '/api/delete-live-entity/$entityId'
      path: '/api/delete-live-entity/$entityId'
      fullPath: '/api/delete-live-entity/$entityId'
      preLoaderRoute: typeof ApiDeleteLiveEntityEntityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/delete-entity/$entityId': {
      id: '/api/delete-entity/$entityId'
      path: '/api/delete-entity/$entityId'
      fullPath: '/api/delete-entity/$entityId'
      preLoaderRoute: typeof ApiDeleteEntityEntityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiBrpRoute: ApiBrpRoute,
  ApiGraphRoute: ApiGraphRoute,
  ApiLiveClientWorldRoute: ApiLiveClientWorldRoute,
  ApiLiveWorldRoute: ApiLiveWorldRoute,
  ApiWorldRoute: ApiWorldRoute,
  ApiDeleteEntityEntityIdRoute: ApiDeleteEntityEntityIdRoute,
  ApiDeleteLiveEntityEntityIdRoute: ApiDeleteLiveEntityEntityIdRoute,
  ApiLiveEntityEntityIdRoute: ApiLiveEntityEntityIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
