# Cargo.toml
[package]
name = "sidereal-core"
version = "0.1.0"
edition = "2021"

# Define features
[features]
default = []
dev = []  # Development features

[dependencies]
bevy = { workspace = true }
bevy_reflect = "0.15.3"
serde = { workspace = true }
serde_json = { workspace = true }
bevy_rapier2d = { version = "0.29.0", features = ["serde-serialize"] }  # Adding Rapier 2D physics engine for Bevy
uuid = { version = "1.4", features = ["v4", "serde"] }

